version: '3'

services:
  kali:
    image: xanonymous/kali
    command: /sbin/init
    container_name: kali-xanonymous
    volumes:
      - home_data:/root
    networks:
      - default
    tmpfs:
      - /run
      - /run/lock
    privileged: true


volumes:
  home_data:

networks:
  default:
